# Generated by Django 2.2.5 on 2019-10-21 21:13

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groupapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodicPay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Periodic pay name')),
                ('when_add', models.DateTimeField(auto_now_add=True, verbose_name='When pay created')),
                ('calc_type', models.PositiveSmallIntegerField(choices=[(0, 'Логика по умолчанию'), (1, 'Пробная логика')], default=0, verbose_name='Script type for calculations')),
                ('amount', models.FloatField(verbose_name='Total amount')),
                ('extra_info', jsonfield.fields.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Periodic pay',
                'verbose_name_plural': 'Periodic pays',
                'db_table': 'periodic_pay',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='Service title')),
                ('descr', models.CharField(max_length=256, verbose_name='Service description')),
                ('speedIn', models.FloatField(db_column='speed_in', default=0.0, verbose_name='Speed In')),
                ('speedOut', models.FloatField(db_column='speed_out', default=0.0, verbose_name='Speed Out')),
                ('amount', models.FloatField(db_column='cost', default=0.0, verbose_name='Price')),
                ('calc_type', models.PositiveSmallIntegerField(choices=[(0, 'Базовый расчётный функционал'), (1, 'IS'), (2, 'Для внутреннего пользования'), (3, 'Услуга на сутки')], default=0, verbose_name='Script')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Tech service')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'db_table': 'services',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='TariffGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(db_column='group_id', on_delete=django.db.models.deletion.CASCADE, to='groupapp.Group')),
                ('tariff', models.ForeignKey(db_column='service_id', on_delete=django.db.models.deletion.CASCADE, to='tariff_app.Tariff')),
            ],
            options={
                'db_table': 'services_groups',
            },
        ),
        migrations.AddField(
            model_name='tariff',
            name='groups',
            field=models.ManyToManyField(blank=True, through='tariff_app.TariffGroup', to='groupapp.Group'),
        ),
        migrations.AlterUniqueTogether(
            name='tariff',
            unique_together={('speedIn', 'speedOut', 'amount', 'calc_type')},
        ),
    ]
