# Generated by Django 2.2.5 on 2019-10-21 21:33

from django.db import migrations, models
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NASModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127, unique=True, verbose_name='Title')),
                ('ip_address', models.GenericIPAddressField(unique=True, verbose_name='Ip address')),
                ('ip_port', models.PositiveSmallIntegerField(verbose_name='Port')),
                ('auth_login', models.CharField(max_length=64, verbose_name='Auth login')),
                ('auth_passw', encrypted_model_fields.fields.EncryptedCharField(verbose_name='Auth password')),
                ('nas_type', models.PositiveSmallIntegerField(choices=[(0, 'Mikrotik NAS')], db_column='gw_type', default=0, verbose_name='Type')),
                ('default', models.BooleanField(db_column='is_default', default=False, verbose_name='Is default')),
                ('enabled', models.BooleanField(default=True, verbose_name='Enabled')),
            ],
            options={
                'verbose_name': 'Network access server. Gateway',
                'verbose_name_plural': 'Network access servers. Gateways',
                'db_table': 'gateways',
                'ordering': ('ip_address',),
            },
        ),
    ]
