# Generated by Django 2.2.5 on 2019-10-21 21:33

import bitfield.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts_app', '0001_initial'),
        ('devapp', '0001_initial'),
        ('tariff_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group_app', '0001_initial'),
        ('gw_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abon',
            fields=[
                ('baseaccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='accounts_app.BaseAccount')),
                ('ballance', models.FloatField(db_column='balance', default=0.0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Ip address')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Comment')),
                ('house', models.CharField(blank=True, max_length=12, null=True, verbose_name='House')),
                ('is_dynamic_ip', models.BooleanField(default=False, verbose_name='Is dynamic ip')),
                ('autoconnect_service', models.BooleanField(db_column='auto_renewal_service', default=False, verbose_name='Automatically connect next service')),
                ('markers', bitfield.models.BitField((('icon_donkey', 'Donkey'), ('icon_fire', 'Fire'), ('icon_ok', 'Ok'), ('icon_king', 'King'), ('icon_tv', 'TV'), ('icon_smile', 'Smile'), ('icon_dollar', 'Dollar'), ('icon_service', 'Service'), ('icon_mrk', 'Marker')), default=0)),
            ],
            options={
                'verbose_name': 'Abon',
                'verbose_name_plural': 'Abons',
                'db_table': 'customers',
                'ordering': ('fio',),
                'permissions': (('can_buy_tariff', 'Buy service perm'), ('can_add_ballance', 'fill account'), ('can_ping', 'Can ping')),
            },
            bases=('accounts_app.baseaccount',),
        ),
        migrations.CreateModel(
            name='AbonRawPassword',
            fields=[
                ('account', models.OneToOneField(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='abonapp.Abon')),
                ('passw_text', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'customer_raw_password',
            },
        ),
        migrations.CreateModel(
            name='PeriodicPayForId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_pay', models.DateTimeField(blank=True, null=True, verbose_name='Last pay time')),
                ('next_pay', models.DateTimeField(verbose_name='Next time to pay')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abonapp.Abon', verbose_name='Account')),
                ('periodic_pay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tariff_app.PeriodicPay', verbose_name='Periodic pay')),
            ],
            options={
                'db_table': 'periodic_pay_for_id',
                'ordering': ('last_pay',),
            },
        ),
        migrations.CreateModel(
            name='PassportInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(re.compile('^-?\\d+\\Z'), code='invalid', message='Enter a valid integer.')], verbose_name='Pasport serial')),
                ('number', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(re.compile('^-?\\d+\\Z'), code='invalid', message='Enter a valid integer.')], verbose_name='Pasport number')),
                ('distributor', models.CharField(max_length=64, verbose_name='Distributor')),
                ('date_of_acceptance', models.DateField(verbose_name='Date of acceptance')),
                ('abon', models.OneToOneField(blank=True, db_column='customer_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='abonapp.Abon')),
            ],
            options={
                'verbose_name': 'Passport Info',
                'verbose_name_plural': 'Passport Info',
                'db_table': 'passport_info',
                'ordering': ('series',),
            },
        ),
        migrations.CreateModel(
            name='InvoiceForPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('amount', models.FloatField(db_column='cost', default=0.0)),
                ('comment', models.CharField(max_length=128)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('date_pay', models.DateTimeField(blank=True, null=True)),
                ('abon', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, to='abonapp.Abon')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Debt',
                'verbose_name_plural': 'Debts',
                'db_table': 'abonent_inv_pay',
                'ordering': ('date_create',),
            },
        ),
        migrations.CreateModel(
            name='AdditionalTelephone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator('^(\\+[7,8,9,3]\\d{10,11})?$')], verbose_name='Telephone')),
                ('owner_name', models.CharField(max_length=127, verbose_name='Telephone owner')),
                ('abon', models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, related_name='additional_telephones', to='abonapp.Abon')),
            ],
            options={
                'verbose_name': 'Additional telephone',
                'verbose_name_plural': 'Additional telephones',
                'db_table': 'additional_telephones',
                'ordering': ('owner_name',),
            },
        ),
        migrations.CreateModel(
            name='AbonTariff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateTimeField(blank=True, db_column='start_time', default=None, null=True)),
                ('deadline', models.DateTimeField(blank=True, default=None, null=True)),
                ('tariff', models.ForeignKey(db_column='service_id', on_delete=django.db.models.deletion.CASCADE, related_name='linkto_tariff', to='tariff_app.Tariff')),
            ],
            options={
                'verbose_name': 'Abon service',
                'verbose_name_plural': 'Abon services',
                'db_table': 'customer_service',
                'ordering': ('time_start',),
                'permissions': (('can_complete_service', 'finish service perm'),),
            },
        ),
        migrations.CreateModel(
            name='AbonStreet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Street title')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group_app.Group', verbose_name='User group')),
            ],
            options={
                'verbose_name': 'Street',
                'verbose_name_plural': 'Streets',
                'db_table': 'customer_street',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='AbonLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('comment', models.CharField(max_length=128)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('abon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abonapp.Abon')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'abonent_log',
                'ordering': ('-date',),
            },
        ),
        migrations.AddField(
            model_name='abon',
            name='current_tariff',
            field=models.OneToOneField(blank=True, db_column='current_service_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='abonapp.AbonTariff'),
        ),
        migrations.AddField(
            model_name='abon',
            name='dev_port',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devapp.Port'),
        ),
        migrations.AddField(
            model_name='abon',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devapp.Device'),
        ),
        migrations.AddField(
            model_name='abon',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='group_app.Group', verbose_name='User group'),
        ),
        migrations.AddField(
            model_name='abon',
            name='last_connected_tariff',
            field=models.ForeignKey(blank=True, db_column='last_connected_service_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tariff_app.Tariff', verbose_name='Last connected service'),
        ),
        migrations.AddField(
            model_name='abon',
            name='nas',
            field=models.ForeignKey(blank=True, db_column='gateway_id', default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gw_app.NASModel', verbose_name='Network access server'),
        ),
        migrations.AddField(
            model_name='abon',
            name='street',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='abonapp.AbonStreet', verbose_name='Street'),
        ),
        migrations.AlterUniqueTogether(
            name='abon',
            unique_together={('ip_address', 'nas')},
        ),
    ]
