# Generated by Django 2.2.5 on 2019-10-21 21:33

from django.db import migrations, models
import django.db.models.deletion
import traf_stat.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abonapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatCache',
            fields=[
                ('last_time', traf_stat.fields.UnixDateTimeField()),
                ('abon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='abonapp.Abon')),
                ('octets', models.PositiveIntegerField(default=0)),
                ('packets', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'flowcache',
                # 'db_tablespace': 'ram',
            },
        ),
    ]
